<h1>Welcome to Duc Bui</h1>
<br><br>
<?php 

$link_1 = $oSeoUrl->rewrite('page-module/content/list',array('page_path'=>'1_6','page_content_id'=>7,'offset'=>2,'page'=>3));

echo $link_1;
echo "<br><a href='{$link_1}'> Detail Link 1</a>";
echo "<br><br><br>";

$link_2 = $oSeoUrl->rewrite('page-module/category/list',array('page_path'=>'1'));
echo $link_2;
echo "<br><a href='{$link_2}'> Detail Link 2</a>";
echo "<br><br><br>";

$link_3 = $oSeoUrl->rewrite('page-module/category/list',array('page_path'=>'1_6'));
echo $link_3;
echo "<br><a href='{$link_3}'> Detail Link 3</a>";
echo "<br><br><br>";


$link_4 = $oSeoUrl->rewrite('page-module/category/list',array('offset'=>2,'page'=>3));
echo $link_4;
echo "<br><a href='{$link_4}'> Detail Link 4</a>";
echo "<br><br><br>";

?>

