<div class="content">

	<div class="header">
		<div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i><?php echo $box_title; ?></h1>
                        <h4> <?php echo $box_title; ?></h4>
                    </div>
        </div>		
	</div>

	<div class="container-fluid">
		<div class="row-fluid">

			<div class="btn-toolbar text-right">
				<a href="<?php echo site_url('home/contact/add'); ?>" class="btn btn-primary"><i class="icon-plus"></i> Thêm mới</a>			
			</div>
			
            <!-- BEGIN Main Content -->
			<div class="row-fluid">
                    <div class="span12">
                    
			<?php echo show_message($notify_msg['msg_title'], $notify_msg['msg_code'] ,$notify_msg['msg_content']); ?>

<!-- 			<div class="alert alert-success fade in"> -->
<!-- 				<button data-dismiss="alert" class="close">×</button> -->
<!-- 				<h4>Success!</h4> -->
<!-- 				<ul> -->
<!--                                             <li>List Item 1</li> -->
<!--                                             <li>List Item 2</li> -->
<!--                                             <li>List Item 3</li> -->
<!--                                             <li>List Item 4</li> -->
<!-- 				</ul> -->
<!-- 			</div> -->
			
<!-- 			<div class="alert alert-success"> -->
<!-- 				<button data-dismiss="alert" class="close">×</button> -->
<!-- 				<strong>Success!</strong> The page has been added. -->
<!-- 			</div>						 -->
                    
                    
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-table"></i><?php echo $box_action; ?></h3>
                                <div class="box-tool">
                                </div>
                            </div>
                            <div class="box-content">
                                <table class="table table-striped table-hover fill-head">
                                    <thead>
                                        <tr>
                                            <th width="2%">#</th>
                                            <th width="3%"></th>
                                            <th width="20%">Name</th>
                                            <th>Title</th>
                                            <th style="width: 100px;text-align: center">Reply</th>                                            											                                           
                                            <th style="width: 70px">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    
                                    <?php
                                    	$i = 1; 
                                    	foreach ($rsContact as $rowContact) :
                                    ?>
                                    
									<tr>
										<td><?php echo $i; ?></td>
										<td></td>
                                        <td>
                                        	<?php echo h($rowContact["fullname"]); ?>
                                        </td>										
                                        <td>
                                        	<?php echo h($rowContact["title"]); ?>
                                        </td>
                                        <td style="text-align: center">
                                            <?php if ($rowContact['active'] == 1) : ?>
                                            	<a href='#' title='Active' class='btn btn-circle btn-lime'><i class="icon-ok-sign"></i></a>
                                            <?php else : ?>
                                            	<a href='#' title='UnActive' class='btn btn-circle btn-gray'><i class="icon-remove-circle"></i></a>
                                            <?php endif; ?>                                            
                                        </td>
										<td>	
											<div class="btn-group">
												<a class="btn btn-small btn-gray" title="" href="<?php echo site_url("home/contact/edit/{$rowContact['id']}")?>"><i class="icon-edit"></i></a>		
												<a class="btn btn-small btn-danger" title="" href="javascript:confimDelete('<?php echo site_url("home/contact/delete/{$rowContact['id']}")?>');"><i class="icon-trash"></i></a>	
											</div>
										</td>
									</tr>                                    
                                    
                                    <?php
                                    		$i++; 
                                    	endforeach; 
                                    ?>
                                        
                                    </tbody>
                                </table>
                            
                            </div>
                            
                        </div>
                    </div>
			</div>
			<!-- END Main Content -->
                			
			
		</div>
	</div>
</div>


