
                <!-- BEGIN Page Title -->
                <div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> Gallery</h1>
                        <h4>Responsive photo gallery using colorbox</h4>
                    </div>
                </div>
                <!-- END Page Title -->

                <!-- BEGIN Main Content -->
                <div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-picture"></i> Gallery</h3>
                            </div>
                            <div class="box-content">
                                <div class="clearfix">
                                    <div class="pull-left">
                                    	<a href="#" class="btn btn-primary show-tooltip" title="" data-original-title="Upload new images"><i class="icon-cloud-upload"></i> Upload</a>
                                    </div>
                                    <div class="pull-right">
                                    	<a href="#" class="btn btn-primary show-tooltip" title="" data-original-title="Upload new images"><i class="icon-cloud-upload"></i> Upload</a>
                                    	<a href="#" class="btn btn-primary show-tooltip" title="" data-original-title="Upload new images"><i class="icon-cloud-upload"></i> Upload 2</a>
                                    </div>
                                </div>

                                <a href="#" class="btn btn-primary show-tooltip" title="" data-original-title="Upload new images"><i class="icon-cloud-upload"></i> Upload</a>
                                
                                <hr>
                                <ul class="gallery">
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/1.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/1_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/2.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/2_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/3.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/3_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/4.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/4_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/5.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/5_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/6.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/6_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/7.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/7_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/8.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/8_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/9.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/9_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                    <li>
                                        <a href="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/10.jpg" rel="prettyPhoto" title="Description of image">
                                            <div>
                                                <img src="http://localhost/z-cms/public_html/admin/flaty_template/img/demo/gallery/10_thumb.jpg" alt="">
                                                <i></i>
                                            </div>
                                        </a>
                                        <div class="gallery-tools">
                                            <a href="#"><i class="icon-link"></i></a>
                                            <a href="#"><i class="icon-paper-clip"></i></a>
                                            <a href="#"><i class="icon-pencil"></i></a>
                                            <a href="#"><i class="icon-trash"></i></a>
                                        </div>
                                    </li>
                                </ul>
                                <div class="pagination pagination-bullet text-center">
                                    <ul>
                                        <li class="active"><a href="#"></a></li>
                                        <li><a href="#"></a></li>
                                        <li><a href="#"></a></li>
                                        <li><a href="#"></a></li>
                                        <li><a href="#"></a></li>
                                        <li><a href="#"></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- END Main Content -->
                

