<div class="content">

	<div class="header">
		<div class="page-title">
                    <div>
                        <h1><i class="icon-file-alt"></i> <?php echo $box_title; ?></h1>
                        <h4><?php echo $box_title; ?></h4>
                    </div>
        </div>		
	</div>

	<div class="container-fluid">
		<div class="row-fluid">

			<div class="btn-toolbar text-right">
				<a href="<?php echo site_url('amway/category/add'); ?>" class="btn btn-primary"><i class="icon-plus"></i> Thêm mới</a>			
			</div>
			
            <!-- BEGIN Main Content -->
			<div class="row-fluid">
                    <div class="span12">
                        <div class="box">
                            <div class="box-title">
                                <h3><i class="icon-table"></i><?php echo $box_action; ?></h3>
                                <div class="box-tool">
                                    <a href="#" data-action="collapse"><i class="icon-chevron-up"></i></a>
                                </div>
                            </div>
                            <div class="box-content">
                                <table class="table table-striped table-hover fill-head">
                                    <thead>
                                        <tr>
                                            <th width="2%">#</th>
                                            <th width="5%"></th>
                                            <th>Name </th>
                                            <th style="width: 70px">Order </th>                                            											
                                            <th style="width: 70px">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                    
                                    <?php
                                    	$i = 1; 
                                    	foreach ($rsCats as $rowCat) :
                                    ?>
                                    
									<tr>
										<td><?php echo $i; ?></td>
										<td></td>
										<td><?php echo h($rowCat["title"]); ?></td>
										<td><?php echo n($rowCat["sort_order"]); ?></td>
										<td>
											<div class='btn-group'>
												<a href="<?php echo site_url("amway/category/edit/{$rowCat['id']}")?>" title='' class='btn btn-small btn-gray'><i class='icon-edit'></i></a>
												<a href="javascript:confimDelete('<?php echo site_url("amway/category/delete/{$rowCat['id']}")?>');" title='' class='btn btn-small btn-danger'><i class='icon-trash'></i></a>
											</div>
										</td>		
										
									</tr>                                    
                                    
                                    <?php
                                    		$i++; 
                                    	endforeach; 
                                    ?>
                                        
                                    </tbody>
                                </table>
                            
<!-- 								<div class="pagination text-left"> -->
<!--                                     <ul> -->
<!--                                         <li><a href="#">← Prev</a></li> -->
<!--                                         <li><a href="#">1</a></li> -->
<!--                                         <li><a href="#">2</a></li> -->
<!--                                         <li class="active"><a href="#">3</a></li> -->
<!--                                         <li><a href="#">4</a></li> -->
<!--                                         <li><a href="#">5</a></li> -->
<!--                                         <li><a href="#">6</a></li> -->
<!--                                         <li><a href="#">Next → </a></li> -->
<!--                                     </ul> -->
<!-- 	                            </div>                             -->
                            
                            </div>
                            
                        </div>
                    </div>
			</div>
			<!-- END Main Content -->
                			
			
		</div>
	</div>
</div>


