<script src="<?php echo __JS_URL; ?>ckeditor/ckeditor.js"></script>

<h1><?= $title; ?></h1>

<table width="100%" border="0" cellpadding="1" cellspacing="1">
	<tr>
		<td width="10%">First Name
		<td><?= h($data['first_name']); ?>
	</tr>
	<tr>
		<td>Last Name
		<td><?= h($data['last_name']); ?>
	</tr>
	<tr>
		<td>Email
		<td><?= h($data['email']); ?>
	</tr>
	<tr>
		<td>Address
		<td><?= h($data['address']); ?>
	</tr>
	<tr>
		<td>Summary
		<td><?= h($data['summary']); ?>
	</tr>
	<tr>
		<td>Content HTML
		<td>
			<?= html($data['description']); ?>
	</tr>			
</table>	


