<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
</head>

<body bgcolor="#FFFFFF">
	
	<table width="100%" cellpadding="0" cellspacing="0" border="0" bgcolor="#3098f0" align="center">
		<tr>
			<td width="20"></td>
			<td>
				<p style="font-family:Arial, Helvetica, sans-serif; color:#fff; font-size:14px; line-height:28px;">
					Chào bạn <?php echo $data['fullname']; ?>, <br>
				</p>
			</td>
			<td width="40"></td>	
		</tr>
				
		<tr height="73">
			<td colspan="3">
				<table width="100%" height="100%" cellpadding="0" cellspacing="0" border="0">

					<tr>
						<td width="40"></td>
						<td>
							<p style="font-family:Arial, Helvetica, sans-serif; color:#fff; font-size:14px; line-height:12px;">
								* <b>Câu hỏi : </b> <?php echo $data['content']; ?> </p>
						</td>								
						<td width="40"></td>
					</tr>
					
					<tr>
						<td width="40"></td>
						<td></td>
						<td width="40"></td>
					</tr>

					<tr>
						<td width="40"></td>
						<td>
							<p style="font-family:Arial, Helvetica, sans-serif; color:#fff; font-size:14px; line-height:12px;">
								* <b>Trả lời : </b> <?php echo $data['answer']; ?> </p>
						</td>								
						<td width="40"></td>
					</tr>
					
				</table>			
			</td>	
		</tr>
		<tr>
			<td width="20"></td>			
			<td>
				<p style="font-family:Arial, Helvetica, sans-serif; color:#fff; font-size:14px; line-height:28px;">
					Trả lời vào <?php echo date("d-m-Y H:i:s"); ?>
				</p>
		
			</td>
			<td width="20"></td>				
		</tr>	
	</table>

</body>
</html>

